# Generated by Django 2.2.1 on 2019-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('x3', models.IntegerField()),
                ('y3', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
