# Generated by Django 2.2.1 on 2019-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passHash', '0003_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
