# Generated by Django 2.2.1 on 2019-06-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passHash', '0007_auto_20190612_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usertb',
        ),
    ]
